spring:
  datasource:
    url: jdbc:h2:mem:testdb #de tras para frente testdb = nome do banco de dados, mem = banco de dados em memoria
    username: sa # nome do usuario = sa
    password: # senha é vazia

  h2:
    console:
      enabled: true # h2 ta habilitado
      path: /h2-console #Caminho para acessar o banco de dados

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true #Habilitar no console para mostrar o comando sql feito no jpa
    properties:
      hibernate:
        format_sql: true #Formatar o comando sql
